spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: 7be5095923bdcdfbf81b
            clientSecret: be8b5a521a5405946bd89edf658c3046dd6cf5e3
          google:
            client-id: google-client-id
            client-secret: google-client-secret
